In [2]:
# fonte da base de dados utilizada: https://www.kaggle.com/datasets/laotse/credit-risk-dataset
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly_express as px

# Padronizar dados:
from sklearn.preprocessing import StandardScaler

In [3]:
base_credit = pd.read_csv("src/credit_risk_dataset.csv")

In [4]:
base_credit['clienteID'] = base_credit.reset_index().index


In [5]:
print(len(base_credit.columns)) 

13


In [6]:
display(base_credit.head(10))
0, 1, 3, 6, 8, 10

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   
5          21           9900                   OWN                2.0   
6          26          77100                  RENT                8.0   
7          24          78956                  RENT                5.0   
8          24          83000                  RENT                8.0   
9          21          10000                   OWN                6.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   
5     VENTURE          A       2500           7.14            1   
6   EDUCATION          B      35000          12.42            1   
7     MEDICAL          B      35000          11.11            1   
8    PERSONAL          A      35000           8.90            1   
9     VENTURE          D       1600          14.74            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  \
0                 0.59                         Y                           3   
1                 0.10                         N                           2   
2                 0.57                         N                           3   
3                 0.53                         N                           2   
4                 0.55                         Y                           4   
5                 0.25                         N                           2   
6                 0.45                         N                           3   
7                 0.44                         N                           4   
8                 0.42                         N                           2   
9                 0.16                         N                           3   

   clienteID  
0          0  
1          1  
2          2  
3          3  
4          4  
5          5  
6          6  
7          7  
8          8  
9          9

(0, 1, 3, 6, 8, 10)

In [7]:
grafico = px.scatter_matrix(base_credit, dimensions=['person_age', 'person_income', 'loan_status'])
grafico.show()

In [8]:
base_credit.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
clienteID                        0
dtype: int64

In [9]:
np.unique(base_credit['loan_grade'])

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype=object)

In [10]:
base_credit = base_credit.drop('loan_int_rate', axis=1)

In [11]:
base_credit['person_emp_length'].fillna(base_credit['person_emp_length'].mean(), inplace=True)

In [12]:
base_credit.shape

(32581, 12)

In [13]:
x_credit = base_credit.iloc[:, [0, 1, 3, 6, 8, 10]].values
y_credit = base_credit.iloc[:, 7].values

In [14]:
display(base_credit.min())
display(base_credit.max())



person_age                                   20
person_income                              4000
person_home_ownership                  MORTGAGE
person_emp_length                           0.0
loan_intent                   DEBTCONSOLIDATION
loan_grade                                    A
loan_amnt                                   500
loan_status                                   0
loan_percent_income                         0.0
cb_person_default_on_file                     N
cb_person_cred_hist_length                    2
clienteID                                     0
dtype: object

person_age                        144
person_income                 6000000
person_home_ownership            RENT
person_emp_length               123.0
loan_intent                   VENTURE
loan_grade                          G
loan_amnt                       35000
loan_status                         1
loan_percent_income              0.83
cb_person_default_on_file           Y
cb_person_cred_hist_length         30
clienteID                       32580
dtype: object

In [15]:
x_credit[:, 0].min(), x_credit[:, 1].min(), x_credit[:, 3].min()

(20.0, 4000.0, 500.0)

In [16]:
x_credit[:, 0].max(), x_credit[:  , 1].max(), x_credit[:  , 3].max()

(144.0, 6000000.0, 35000.0)

In [17]:
scaler = StandardScaler()
x_credit = scaler.fit_transform(x_credit)

In [18]:
print(x_credit)

[[-0.90337383 -0.11414329 28.93573761  4.01940376  3.9314108  -0.69155444]
 [-1.06090423 -0.91114671  0.05148097 -1.35864998 -0.65745847 -0.93816728]
 [-0.43078263 -0.91114671 -0.92764637 -0.64684875  3.74411001 -0.69155444]
 ...
 [ 5.87043346  0.16012914 -0.4380827   4.01940376  2.71395568  5.47376651]
 [ 4.45265984  1.35402091  0.05148097  0.85584274 -0.65745847  4.98054084]
 [ 6.02796387 -0.38841572 -0.68286453 -0.49262515 -0.1892065   5.96699219]]
